teezo

diff --git a/0x00-hello_world/100-intel b/0x00-hello_world/100-intel
--- a/0x00-hello_world/100-intel
+++ b/0x00-hello_world/100-intel
@@ -1,2 +1,10 @@
 #!/bin/bash
+read -p $CFILE
 gcc $CFILE -o cisfun
+if [ $? -eq 0 ]
+	 echo "Compilation successful. Executable created:
+cisfun"
+else
+	 echo "Compilation failed."
+fi
+# End of script
